name: Push Docker Image to Artifact Registry

on:
  workflow_run:
    workflows: ["Authenticate with GCP"]
    types:
      - completed
 
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CI_SERVICE_ACCOUNT_KEY }}

      - name: Configure Docker to use gcloud as a credential helper
        run: |
          gcloud auth configure-docker

      - name: Check if the repository exists
        id: check_repo
        run: |
          if gcloud artifacts repositories describe ${{ env.REPOSITORY_NAME }} --location=${{ env.LOCATION }} >/dev/null 2>&1; then
            echo "::set-output name=exists::true"
          else
            echo "::set-output name=exists::false"
          fi

      - name: Build Docker image
        run: |
          docker build -t ${{ env.LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/myimage:latest .
          
      - name: Push Docker image to Artifact Registry
        run: |
          docker push ${{ env.LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/myimage:latest
